// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {launcher} from '../models';
import {context} from '../models';

export function CompleteDeviceCodeLogin(arg1:string):Promise<void>;

export function CreateInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteInstance(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.AccountInfo>>;

export function GetActiveAccount():Promise<main.AccountInfo>;

export function GetGlobalSettings():Promise<main.GlobalSettings>;

export function GetInstanceSettings(arg1:string):Promise<launcher.InstanceConfig>;

export function GetInstances():Promise<Array<launcher.Instance>>;

export function GetLaunchProgress():Promise<main.LaunchProgress>;

export function GetLoaderVersions(arg1:string,arg2:string):Promise<Array<main.LoaderVersion>>;

export function GetMinecraftVersions(arg1:main.VersionFilters):Promise<Array<main.MinecraftVersion>>;

export function GetModpacks():Promise<Array<main.Modpack>>;

export function GetRunningInstances():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InstallModpack(arg1:main.Modpack,arg2:string):Promise<void>;

export function IsInstanceRunning(arg1:string):Promise<boolean>;

export function KillInstance(arg1:string):Promise<void>;

export function LaunchInstance(arg1:string,arg2:string):Promise<void>;

export function LoginOffline(arg1:string):Promise<void>;

export function LoginToDeviceCode():Promise<Record<string, any>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RenameInstance(arg1:string,arg2:string):Promise<void>;

export function SaveGlobalSettings(arg1:main.GlobalSettings):Promise<void>;

export function SaveInstanceSettings(arg1:string,arg2:launcher.InstanceConfig):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function ShowDialog(arg1:string,arg2:string):Promise<void>;

export function ShowOfflineLoginDialog():Promise<Record<string, any>>;
