// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteDeviceCodeLogin(arg1) {
  return window['go']['main']['App']['CompleteDeviceCodeLogin'](arg1);
}

export function CreateInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3, arg4);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetInstanceSettings(arg1) {
  return window['go']['main']['App']['GetInstanceSettings'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetLaunchProgress() {
  return window['go']['main']['App']['GetLaunchProgress']();
}

export function GetLoaderVersions(arg1, arg2) {
  return window['go']['main']['App']['GetLoaderVersions'](arg1, arg2);
}

export function GetMinecraftVersions(arg1) {
  return window['go']['main']['App']['GetMinecraftVersions'](arg1);
}

export function GetModpacks() {
  return window['go']['main']['App']['GetModpacks']();
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallModpack(arg1, arg2) {
  return window['go']['main']['App']['InstallModpack'](arg1, arg2);
}

export function IsInstanceRunning(arg1) {
  return window['go']['main']['App']['IsInstanceRunning'](arg1);
}

export function KillInstance(arg1) {
  return window['go']['main']['App']['KillInstance'](arg1);
}

export function LaunchInstance(arg1, arg2) {
  return window['go']['main']['App']['LaunchInstance'](arg1, arg2);
}

export function LoginOffline(arg1) {
  return window['go']['main']['App']['LoginOffline'](arg1);
}

export function LoginToDeviceCode() {
  return window['go']['main']['App']['LoginToDeviceCode']();
}

export function OnStartup(arg1) {
  return window['go']['main']['App']['OnStartup'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameInstance(arg1, arg2) {
  return window['go']['main']['App']['RenameInstance'](arg1, arg2);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveInstanceSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveInstanceSettings'](arg1, arg2);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowDialog'](arg1, arg2);
}

export function ShowOfflineLoginDialog() {
  return window['go']['main']['App']['ShowOfflineLoginDialog']();
}
